replace_color: false
normal-emojis:
  # Emojis without colons
  default:
    o/: "&dhi&r"

unnormal-emojis:
  # Emojis with colons
  default:
    lenny: "&3( ͡° ͜ʖ&5 ͡°)"
    shrug: "¯\\_(ツ)_/¯"
  mvp:
    tableflip: "(╯°□°）╯︵ ┻━┻"