name: ToastedEmojis
version: '${project.version}'
main: me.serbob.toastedemojis.ToastedEmojis
api-version: 1.19
authors: [ Serbob ]
description: A simple, customizable emoji/anti-swearing system.
website: https://www.spigotmc.org/resources/toastedemoji-swearing-filter-emojis.107047/
commands:
  toastedemojis:
    description: Reload the ToastedEmojis config.
  toastedemojis.reload:
    permission: toastedemojis.reload
  toastedemojis.list:
    permission: toastedemojis.list